import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#fafaf8',
  '--slot4-page-text': '#1a1a1a',
  '--slot4-panel-bg': '#f2f1ed',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#6b6b6b',
  '--slot4-soft-muted-text': '#999999',
  '--slot4-accent': '#3ecfb4',
  '--slot4-accent-fill': '#3ecfb4',
  '--slot4-accent-soft': '#e8f8f4',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#1a1a1a',
  '--slot4-dark-text': '#f5f5f3',
  '--slot4-media-bg': '#f2f1ed',
  '--slot4-cream': '#fafaf8',
  '--slot4-warm': '#f2f1ed',
  '--slot4-lavender': '#fafaf8',
  '--slot4-gray': '#f2f1ed',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#fafaf8',
  '--editable-page-text': '#1a1a1a',
  '--editable-container': '1280px',
  '--editable-border': '#e5e5e0',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#1a1a1a',
  '--editable-nav-active': '#3ecfb4',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#1a1a1a',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#1a1a1a',
  '--editable-footer-text': '#f5f5f3',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_3px_rgba(0,0,0,0.06)]',
  shadowStrong: 'shadow-[0_4px_18px_rgba(0,0,0,0.10)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-medium uppercase tracking-[0.18em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-normal leading-[1.1] tracking-[-0.01em] sm:text-5xl lg:text-[3.5rem]',
    sectionTitle: 'text-3xl font-normal tracking-[-0.01em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `${editablePalette.darkBg} ${editablePalette.darkText}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 bg-[var(--slot4-dark-bg)] px-6 py-3 text-sm font-medium text-[var(--slot4-dark-text)] transition duration-200 hover:opacity-90 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-medium text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-page-text)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 ${editablePalette.accentBg} px-6 py-3 text-sm font-medium text-[var(--slot4-on-accent)] transition duration-200 hover:opacity-90 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-0.5 hover:shadow-[0_8px_28px_rgba(0,0,0,0.08)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
